### ISSUE TITLE
Resource owner credentials grant is expecting client_id and client_token

### ISSUE THREAD

**Issue by prem-prakash** [danschultzer/ex_oauth2_provider#16]
Still learning, but it seems to me that Resource owner credentials grant type (grant_type=password) should not require client_id and client_token

Does it make sense?

But it is being required on :

https://github.com/danschultzer/ex_oauth2_provider/blob/master/lib/ex_oauth2_provider/oauth2/token/utils.ex#L10

ref: https://tools.ietf.org/html/rfc6749#section-4.3

**Comment by danschultzer** [comment]
You're right, `client_secret` has to be optional.

The rule is that client secret is not to be used if it hasn't been issued, and there's a recommendation that you shouldn't use client secret if you authenticate with a public client like a mobile application.

For context here are some different sources on authentication and password grant.

https://aaronparecki.com/oauth-2-simplified/
> Note, the client secret is not included here under the assumption that most of the use cases for password grants will be mobile or desktop apps, where the secret cannot be protected.

https://www.oauth.com/oauth2-servers/access-tokens/password-grant/:
> If the client was issued a secret, then the client must authenticate this request. Typically the service will allow either additional request parameters client_id and client_secret, or accept the client ID and secret in the HTTP Basic auth header.

rfc6749:
>  If the client type is confidential or the client was issued client
>   credentials (or assigned other authentication requirements), the
>   client MUST authenticate with the authorization server as described
>   in Section 3.2.1.

And some code:
https://github.com/doorkeeper-gem/doorkeeper/blob/c846335ad75f2f9c7108e577cb84eaf8ab66b86f/lib/doorkeeper/request/password.rb#L19-L24
https://github.com/oauthjs/node-oauth2-server/blob/e1f741fdad191ee47e7764b80a8403c1ea2804d4/lib/handlers/token-handler.js#L131-L133

Doorkeeper [doesn't seem to do this in a safe way](https://github.com/doorkeeper-gem/doorkeeper/blob/c846335ad75f2f9c7108e577cb84eaf8ab66b86f/spec/requests/flows/password_spec.rb#L38), since you can use only `client_id` even if the secret has been issued. 

I'll patch this so `client_secret` is not required to be set in the request, but it'll still validate against it if it exists in the database. You can omit the `client_secret` param if the `client_secret` is an empty string in the database, but otherwise, it'll be required.

**Comment by danschultzer** [comment]
@prem-prakash I've created PR #17 to fix this. Let me know if this fix works for you, then I'll release a new version.

**Comment by danschultzer** [comment]
When creating the application you can just use `%{secret: ""}`, and it will not auto-generate a new secret.

**Comment by prem-prakash** [comment]
@danschultzer I tried your branch and it worked perfectly here, thank you

**Comment by danschultzer** [comment]
Thanks! `v0.2.1` has been released.
