### ISSUE TITLE
Setting `:use_refresh_token` in config not working

### ISSUE THREAD

**Issue by blatyo** [danschultzer/ex_oauth2_provider#62]
I noticed on this line, that it's looking for `:use_refresh_token` in params rather than config.

https://github.com/danschultzer/ex_oauth2_provider/blob/master/lib/ex_oauth2_provider/access_tokens/access_token.ex#L77

This appears to be why refresh_token's aren't being generated.

**Comment by danschultzer** [comment]
It's because it's passed along as param, since some strategies (like [client credentials](https://github.com/danschultzer/ex_oauth2_provider/blob/d602d8ea7592a9188939f841f5a57a7f29d856a2/lib/ex_oauth2_provider/oauth2/token/strategy/client_credentials.ex#L37)) must not permit refresh token.

There should be tests for it in all strategies, e.g. here's for the code flow strategy (this was some of the earliest code I wrote in elixir so not very idiomatic if `refute is_nil`):

https://github.com/danschultzer/ex_oauth2_provider/blob/d602d8ea7592a9188939f841f5a57a7f29d856a2/test/ex_oauth2_provider/oauth2/token/strategy/authorization_code_test.exs#L36-L46

**Comment by blatyo** [comment]
I see. We were creating access tokens directly from `AccessTokens.create_token/3`, because we're migrating users from one system into another specifically for auth. So, it was surprising to us when we noticed we didn't have refresh tokens, but had configured it.

**Comment by danschultzer** [comment]
Yeah, it's confusing. I should had called it something different in the db than what it's called in the config. I mostly just ported it straight from doorkeeper.
